# Site settings
title: Tango Mints 
email:

description: > # this means to ignore newlines until "baseurl:"
  Tango Mint is a fund-raising project for Tangueros Foundation
  project grants

baseurl: "" # the subpath of your site, e.g. /blog/

url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
